project:
  type: website
  output-dir: docs

website:
  title: "Learning Azure Networks"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - topics.qmd
  sidebar:
    - title: "Home"
      style: "docked"
      background: light
      contents:
        - text: "---"
        - topics.qmd        
        - text: "---"
        - topics/defense-in-depth-matching.qmd
        - text: "---"
        - topics/gather-network-requirements.qmd        
        - text: "---"
        - topics/vpn-connection.qmd
        - text: "---"
        - topics/azure-expressroute-and-expressroute-direct-connection.qmd
        - text: "---"
        - topics/azure-expressroute-with-vpn-failover.qmd
        - text: "---"
        - topics/azure-virtual-wan.qmd
        - text: "---"
        - topics/global-transit-network-with-azure-virtual-wan.qmd
        - text: "---"
        - topics/design-azure-virtual-networks.qmd
        - text: "---"
        - topics/design-network-topology.qmd
        - text: "---"
        - topics/design-outbound-connectivity.qmd
        - text: "---"
        - topics/choosing-a-load-balancer-solution.qmd
        - text: "---"
        - topics/load-balancing-options.qmd
        - text: "---"
        - topics/azure-load-balancer.qmd        
        - text: "---"
        - topics/azure-application-gateway.qmd
        - text: "---"
        - topics/azure-content-delivery-network.qmd
        - text: "---"
        - topics/azure-front-door-service.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
